apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 65.x
      helm:
        values: |
          nameOverride: prometheus

          alertmanager:
            enabled: false

          grafana:
            enabled: true
            adminPassword: admin
            deploymentStrategy:
              type: RollingUpdate
              rollingUpdate:
                maxSurge: 0
                maxUnavailable: 1
            grafana.ini:
              server:
                root_url: https://grafana.agffa.ca
            ingress:
              enabled: true
              ingressClassName: traefik
              annotations:
                traefik.ingress.kubernetes.io/router.entrypoints: websecure
                traefik.ingress.kubernetes.io/router.tls: "true"
                traefik.ingress.kubernetes.io/router.middlewares: traefik-authentik-forwardauth@kubernetescrd
                cert-manager.io/cluster-issuer: letsencrypt-production
              hosts:
                - grafana.agffa.ca
              tls:
                - secretName: grafana-tls
                  hosts:
                    - grafana.agffa.ca
            persistence:
              enabled: true
              storageClassName: longhorn
              size: 5Gi
            sidecar:
              dashboards:
                enabled: true
                searchNamespace: ALL
            additionalDataSources:
              - name: Longhorn
                type: prometheus
                url: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
                access: proxy

          prometheus:
            prometheusSpec:
              retention: 15d
              storageSpec:
                volumeClaimTemplate:
                  spec:
                    storageClassName: longhorn
                    accessModes: [ReadWriteOnce]
                    resources:
                      requests:
                        storage: 20Gi
              serviceMonitorSelectorNilUsesHelmValues: false
              podMonitorSelectorNilUsesHelmValues: false

          nodeExporter:
            enabled: true

          kubeStateMetrics:
            enabled: true

    - repoURL: https://github.com/ItsRyanG/homelab-infra.git
      targetRevision: master
      path: monitoring/k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
