apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-blueprints
  namespace: authentik
data:
  traefik-forwardauth.yaml: |
    version: 1
    metadata:
      name: traefik-forwardauth
    entries:
      - model: authentik_providers_proxy.proxyprovider
        state: present
        identifiers:
          name: traefik-forwardauth
        attrs:
          name: traefik-forwardauth
          authentication_flow: !Find [authentik_flows.flow, [slug, default-authentication-flow]]
          authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]
          mode: forward_domain
          external_host: https://authentik.agffa.ca
          cookie_domain: agffa.ca

      - model: authentik_core.application
        state: present
        identifiers:
          slug: traefik-forwardauth
        attrs:
          name: Traefik ForwardAuth
          slug: traefik-forwardauth
          provider: !Find [authentik_providers_proxy.proxyprovider, [name, traefik-forwardauth]]

      - model: authentik_outposts.outpost
        state: present
        identifiers:
          name: authentik Embedded Outpost
        attrs:
          name: authentik Embedded Outpost
          type: proxy
          providers:
            - !Find [authentik_providers_proxy.proxyprovider, [name, traefik-forwardauth]]
