apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: crowdsec-bouncer
  namespace: traefik
spec:
  plugin:
    bouncer:
      enabled: true
      logLevel: INFO
      updateIntervalSeconds: 60
      crowdsecMode: live
      crowdsecLapiKey: "REPLACE_WITH_BOUNCER_KEY"
      crowdsecLapiHost: crowdsec-service.crowdsec.svc.cluster.local:8080
      crowdsecLapiScheme: http
      forwardedHeadersTrustedIPs:
        - 10.42.0.0/16
